services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Command\:
        resource: '../../src/Command'

    App\Command\ExtendedClassesAnnotationsCommand:
        arguments:
            - '%shopsys.root_dir%'

    Shopsys\FrameworkBundle\Command\ExtendedClassesAnnotationsCommand: '@App\Command\ExtendedClassesAnnotationsCommand'

    Shopsys\FrameworkBundle\Component\ClassExtension\ClassExtensionRegistry:
        arguments:
            - '%shopsys.entity_extension.map%'
            - '%shopsys.framework.root_dir%'

    Shopsys\FrameworkBundle\Command\RecalculationsCommand: '@App\Command\RecalculationsCommand'
