services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Model\Product\Transfer\ProductImageImportCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Import obrázků k produktům z Pohoda IS', instanceName: images }
