services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ###########################
    ## DEFAULT CRON INSTANCE ##
    ###########################

    App\Model\GoPay\GoPayAvailablePaymentsCronModule:
        arguments:
            - '%gopay_config%'
        tags:
            - { name: shopsys.cron, hours: '3', minutes: '50', readableName: 'Stažení GoPay platebních metod' }

    App\Component\Balikobot\Pickup\DownloadPickupPlacesCronModule:
        tags:
            - { name: shopsys.cron, hours: '1', minutes: '00', readableName: 'Stažení Balikobot odběrných míst' }

    #    App\Model\Product\Mall\MallProductExportCronModule:
    #        tags:
    #            - { name: shopsys.cron, hours: '23', minutes: '00' }

    Shopsys\FrameworkBundle\Model\Product\Availability\ProductAvailabilityCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Přepočet dostupností produktů' }

    Shopsys\FrameworkBundle\Model\Product\ProductVisibilityImmediateCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Přepočet viditelností produktů (pouze produkty označené k přepočtu)' }

    #    App\Model\Product\Mall\MallProductDeleteCronModule:
    #        tags:
    #            - { name: shopsys.cron, hours: '23', minutes: '00', readableName: 'Smazání produktů z Mall' }

    #################################
    ## PAYMENT GATES CRON INSTANCE ##
    #################################

    App\Model\GoPay\OrderGoPayStatusUpdateCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '15', instanceName: customers, readableName: 'Aktualizace objednávek pro platby GoPay' }

    App\Model\PayPal\OrderPayPalStatusUpdateCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '15', instanceName: customers, readableName: 'Aktualizace objednávek pro platby PayPal' }

    #####################################
    ## PRODUCTS TRANSFER CRON INSTANCE ##
    #####################################

    App\Model\Product\Transfer\ProductImportCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Import změněných produktů z Pohoda IS' }

    ######################################

    Shopsys\FrameworkBundle\Model\Product\Elasticsearch\ProductExportCronModule:
        tags:
            - { name: shopsys.cron, hours: '0', minutes: '0', readableName: "Export všech produktů do Elasticsearch" }

    #########################
    ## CATEGORIES TRANSFER ##
    #########################
    App\Model\Category\Transfer\CategoryImportCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Import změněných kategorií z Pohoda IS' }

    #########################

    Shopsys\FrameworkBundle\Model\Feed\DailyFeedCronModule: ~

    overriddenDailyFeedCronModule:
        class: App\Model\Feed\DailyFeedCronModule
        tags:
            - { name: shopsys.cron, hours: '*/6', minutes: '0', readableName: 'Generování denních feedů' }

    Shopsys\FrameworkBundle\Model\Feed\HourlyFeedCronModule: ~

    overriddenHourlyFeedCronModule:
        class: Shopsys\FrameworkBundle\Model\Feed\HourlyFeedCronModule
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '10', readableName: 'Generování hodinových feedů' }

    Shopsys\FrameworkBundle\Model\Sitemap\SitemapCronModule: ~

    overriddenSitemapCronModule:
        class: Shopsys\FrameworkBundle\Model\Sitemap\SitemapCronModule
        tags:
            - { name: shopsys.cron, hours: '4', minutes: '0', readableName: 'Generování sitemap' }

    Shopsys\FrameworkBundle\Model\Pricing\Vat\VatDeletionCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Smazání starých sazeb DPH' }

    Shopsys\FrameworkBundle\Model\Product\Pricing\ProductPriceCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Přepočet cen produktů' }

    Shopsys\FrameworkBundle\Model\Product\ProductVisibilityMidnightCronModule:
        tags:
            - { name: shopsys.cron, hours: '0', minutes: '0', readableName: 'Přepočet viditelností produktů (všechny produkty)' }

    App\Model\Product\ProductRefreshCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Přeuložení označených produktů pro správný přepočet přiřazení výprodejových štítků apod.' }

    Shopsys\FrameworkBundle\Model\Product\Elasticsearch\ProductExportChangedCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: "Export změněných produktů do Elasticsearch" }

    Shopsys\FrameworkBundle\Model\Cart\Item\DeleteOldCartsCronModule:
        tags:
            - { name: shopsys.cron, hours: '0', minutes: '0', readableName: 'Smazání starých košíků' }

    # This module should run as last because it creates multiple kernels and fake requests.
    Shopsys\FrameworkBundle\Component\Error\ErrorPageCronModule:
        tags:
            - { name: shopsys.cron, hours: '21', minutes: '10', readableName: 'Vygenerování chybových stránek' }

    App\Model\Order\Transfer\OrderExportCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*' }
