services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ###########################
    ## DEFAULT CRON INSTANCE ##
    ###########################

    App\Model\GoPay\GoPayAvailablePaymentsCronModule:
        arguments:
            - '%gopay_config%'
        tags:
            - { name: shopsys.cron, hours: '3', minutes: '50', readableFrequency: '1x za den' }

    App\Component\Balikobot\Pickup\DownloadPickupPlacesCronModule:
        tags:
            - { name: shopsys.cron, hours: '1', minutes: '00', readableFrequency: 'v 01:00 a při změně dopravy' }

    #    App\Model\Product\Mall\MallProductExportCronModule:
    #        tags:
    #            - { name: shopsys.cron, hours: '23', minutes: '00' }

    Shopsys\FrameworkBundle\Model\Product\Availability\ProductAvailabilityCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Recalculate product availabilities' }

    Shopsys\FrameworkBundle\Model\Product\ProductVisibilityImmediateCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Recalculate immediate product visibilities' }

    App\Model\Product\Mall\MallProductDeleteCronModule:
        tags:
            - { name: shopsys.cron, hours: '23', minutes: '00' }

    #################################
    ## PAYMENT GATES CRON INSTANCE ##
    #################################

    App\Model\GoPay\OrderGoPayStatusUpdateCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '15', instanceName: customers, readableFrequency: '1x za hodinu' }

    App\Model\PayPal\OrderPayPalStatusUpdateCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '15', instanceName: customers, readableFrequency: '1x za hodinu' }

    #####################################
    ## PRODUCTS TRANSFER CRON INSTANCE ##
    #####################################

    App\Model\Product\Transfer\ProductImportCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*' }

    ######################################

    Shopsys\FrameworkBundle\Model\Product\Elasticsearch\ProductExportCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: "Export all products to Elasticsearch" }

    #########################
    ## CATEGORIES TRANSFER ##
    #########################
    App\Model\Category\Transfer\CategoryImportCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*' }

    #########################

    Shopsys\FrameworkBundle\Model\Feed\DailyFeedCronModule: ~

    overriddenDailyFeedCronModule:
        class: App\Model\Feed\DailyFeedCronModule
        tags:
            - { name: shopsys.cron, hours: '*/6', minutes: '0', readableName: 'Generate daily feeds' }

    Shopsys\FrameworkBundle\Model\Feed\HourlyFeedCronModule: ~

    overriddenHourlyFeedCronModule:
        class: Shopsys\FrameworkBundle\Model\Feed\HourlyFeedCronModule
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '10', readableName: 'Generate hourly feeds' }

    Shopsys\FrameworkBundle\Model\Sitemap\SitemapCronModule: ~

    overriddenSitemapCronModule:
        class: Shopsys\FrameworkBundle\Model\Sitemap\SitemapCronModule
        tags:
            - { name: shopsys.cron, hours: '4', minutes: '0', readableName: 'Generate Sitemap' }

    Shopsys\FrameworkBundle\Model\Pricing\Vat\VatDeletionCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Delete vats' }

    Shopsys\FrameworkBundle\Model\Product\Pricing\ProductPriceCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Recalculate product prices' }

    Shopsys\FrameworkBundle\Model\Product\ProductVisibilityMidnightCronModule:
        tags:
            - { name: shopsys.cron, hours: '0', minutes: '0', readableName: 'Recalculate midnight product visibilities' }

    Shopsys\FrameworkBundle\Model\Product\Elasticsearch\ProductExportChangedCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: "Export changed products to Elasticsearch" }

    Shopsys\ProductFeed\HeurekaBundle\Model\HeurekaCategory\HeurekaCategoryCronModule:
        tags:
            - { name: shopsys.cron, hours: '3', minutes: '0', readableName: 'Download Heureka categories' }

    Shopsys\FrameworkBundle\Model\Cart\Item\DeleteOldCartsCronModule:
        tags:
            - { name: shopsys.cron, hours: '0', minutes: '0', readableName: 'Delete old customer carts' }

    # This module should run as last because it creates multiple kernels and fake requests.
    Shopsys\FrameworkBundle\Component\Error\ErrorPageCronModule:
        tags:
            - { name: shopsys.cron, hours: '21', minutes: '10', readableName: 'Generate Error pages' }
