services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Model\Feed\Mergado\MergadoFeedInfo: ~

    App\Model\Feed\Mergado\MergadoFeed:
        tags:
            - { name: shopsys.product_feed }
