parameters:
    fp_js_form_validator.twig_extension.class: 'App\Twig\JsFormValidatorTwigExtension'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Twig\:
        resource: '../../src/Twig/'
        exclude: '../../src/Twig/{JsFormValidatorTwigExtension.php}'

    App\Twig\ImageExtension:
        arguments:
            $frontDesignImageUrlPrefix: '%shopsys.front_design_image_url_prefix%'
            $assetsPackage: '@assets._default_package'
            $isLazyLoadEnabled: '%shopsys.image.enable_lazy_load%'

    App\Twig\DomainExtension:
        arguments:
            - '%shopsys.domain_images_url_prefix%'
