framework:
    annotations:
        cache: shopsys.framework.cache_driver.annotations_cache
    secret: "%secret%"
    router:
        strict_requirements: true
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    trusted_hosts: ~
    session:
        handler_id: snc_redis.session.handler
        cookie_httponly: true
        # Disable the default PHP session garbage collection.
        # Session garbage collection is responsibility of hosting.
        gc_probability: 0
    fragments: ~
    http_method_override: true
    profiler:
        enabled: false
        collect: false
    assets:
        base_urls:
            # When you do not want to use CDN, it is used value '//' as workaround by https://github.com/symfony/symfony/issues/28391
            - '%env(CDN_DOMAIN)%'
    error_controller: 'App\Controller\Front\ErrorController::showAction'
