snc_redis:
    clients:
        bestselling_products:
            type: 'phpredis'
            alias: 'bestselling_products'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:cache:bestselling_products:'
        doctrine_metadata:
            type: 'phpredis'
            alias: 'doctrine_metadata'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:cache:doctrine:metadata:'
        doctrine_query:
            type: 'phpredis'
            alias: 'doctrine_query'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:cache:doctrine:query:'
        friendly_url:
            type: 'phpredis'
            alias: 'friendly_url'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:cache:friendly_url:'
        global:
            type: 'phpredis'
            alias: 'global'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%'
        session:
            type: 'phpredis'
            alias: 'session'
            dsn: 'redis://%redis_host%'
        framework_annotations:
            type: 'phpredis'
            alias: 'framework_annotations'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:cache:framework:annotations:'
        twig:
            type: 'phpredis'
            alias: 'twig'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:cache:twig:'
    session:
        client: 'session'
        prefix: '%env(REDIS_PREFIX)%session:'
