front_cart_add_product:
    path: /cart/addProduct/
    defaults: { _controller: App\Controller\Front\CartController:addProductAction }
    methods: [POST]

front_cart_add_product_ajax:
    path: /cart/addProductAjax/
    defaults: { _controller: App\Controller\Front\CartController:addProductAjaxAction }
    methods: [POST]

front_cart_box:
    path: /cart/box/
    defaults: { _controller: App\Controller\Front\CartController:boxAction }

front_cart_content:
    path: /cart/box-content/
    defaults: { _controller: App\Controller\Front\CartController:boxContentAction }
    condition: "request.isXmlHttpRequest()"

front_cart_delete:
    path: /cart/delete/{cartItemId}/
    defaults: { _controller: App\Controller\Front\CartController:deleteAction }
    requirements:
        cartItemId: \d+

front_contact_form_send:
    path: /contactForm/
    defaults: { _controller: App\Controller\Front\ContactFormController:sendAction }
    methods: [POST]
    condition: "request.isXmlHttpRequest()"

front_customer_login_as_remembered_user:
    # same path must be in security.yaml
    path: /login-as-remembered-user/
    defaults: { _controller: App\Controller\Front\CustomerController:loginAsRememberedUserAction}

front_error_page:
    path: /_error/{code}/
    defaults: { _controller: App\Controller\Front\ErrorController:errorPageAction}
    requirements:
        code: \d+

front_error_page_format:
    path: /_error/{code}/{_format}/
    defaults: { _controller: App\Controller\Front\ErrorController:errorPageAction}
    requirements:
        code: \d+
        _format: css|html|js|json|txt|xml

front_homepage:
    path: /
    defaults: { _controller: App\Controller\Front\HomepageController:indexAction }

front_image:
    path: /%shopsys.content_dir_name%/images/{entityName}/{type}/{sizeName}/{imageId}.{extension}
    defaults: { _controller: App\Controller\Front\ImageController:getImageAction }

front_additional_image:
    path: /%shopsys.content_dir_name%/images/{entityName}/{type}/{sizeName}/additional_{additionalIndex}_{imageId}.{extension}
    defaults: { _controller: App\Controller\Front\ImageController:getAdditionalImageAction }
    requirements:
        additionalIndex: \d+

front_image_without_type:
    path: /%shopsys.content_dir_name%/images/{entityName}/{sizeName}/{imageId}.{extension}
    defaults:
        _controller: App\Controller\Front\ImageController:getImageAction
        type: ~

front_additional_image_without_type:
    path: /%shopsys.content_dir_name%/images/{entityName}/{sizeName}/additional_{additionalIndex}_{imageId}.{extension}
    defaults:
        _controller: App\Controller\Front\ImageController:getAdditionalImageAction
        type: ~
    requirements:
        additionalIndex: \d+

front_login_check:
    path: /login/check/
# controller's action is unnecessary, because firewall processes whole request

front_newsletter_send:
    path: /newsletter/subscribe-email/
    defaults: { _controller: App\Controller\Front\NewsletterController:subscribeEmailAction }
    methods: [POST]
    condition: "request.isXmlHttpRequest()"

front_order_change_payment_method:
    path: /order/change-payment-method/{urlHash}
    defaults: { _controller: App\Controller\Front\OrderController:changePaymentAction }
    methods: [POST]

front_order_gopay_status_notify:
    path: /order/gopay-status-notify/{orderId}
    defaults: { _controller: App\Controller\Front\GoPayController:gopayStatusNotifyAction }
    methods: [GET]

front_order_preview:
    path: /order/preview/
    defaults: { _controller: App\Controller\Front\OrderController:previewAction }
    condition: "request.isXmlHttpRequest()"
    methods: [GET]

front_order_save_form:
    path: /order/save-form/
    defaults: { _controller: App\Controller\Front\OrderController:saveOrderFormAction }
    methods: [POST]

front_order_terms_and_conditions:
    path: /order/terms-and-conditions/
    defaults: { _controller: App\Controller\Front\OrderController:termsAndConditionsAction }

front_order_terms_and_conditions_download:
    path: /order/terms-and-conditions-download/
    defaults: { _controller: App\Controller\Front\OrderController:TermsAndConditionsDownloadAction }

front_order_transport_and_payment_box:
    path: /order/transport-and-payment-box/
    defaults: { _controller: App\Controller\Front\OrderController:transportAndPaymentBoxAction }

front_promo_code_apply:
    path: /promo-code/apply/
    defaults: { _controller: App\Controller\Front\PromoCodeController:applyAction }
    methods: [POST]

front_promo_code_remove:
    path: /promo-code/remove/
    defaults: { _controller: App\Controller\Front\PromoCodeController:removeAction }

front_robots_txt:
    path: /robots.txt
    defaults: { _controller: App\Controller\Front\RobotsController:indexAction }

front_registration_exists_email:
    path: /registration/exists-email
    defaults: { _controller: App\Controller\Front\RegistrationController:existsEmailAction }
    methods: [POST]

front_export_personal_data:
    path: /personal-overview-export/xml/{hash}
    defaults: { _controller: App\Controller\Front\PersonalDataController:exportXmlAction }

front_login_window_form:
    path: /login/form
    defaults: { _controller: App\Controller\Front\LoginController:windowFormAction }
    methods: [POST]

front_order_paypal_status_notify:
    path: /order/paypal-status-notify/{orderId}
    defaults: { _controller: App\Controller\Front\PayPalController:payPalStatusNotifyAction }
    methods: [GET]

front_pickup_place_search:
    path: /pickup-place/search/
    defaults: { _controller: App\Controller\Front\PickupPlaceController:searchAction }
    condition: "request.isXmlHttpRequest()"

front_pickup_place_autocomplete:
    path: /pickup-place/autocomplete/
    defaults: { _controller: App\Controller\Front\PickupPlaceController:autocompleteAction }
    methods: [POST]
    condition: "request.isXmlHttpRequest()"

front_store_list:
    path: /store/list/
    defaults: { _controller: App\Controller\Front\StoreController:listAction }
    condition: "request.isXmlHttpRequest()"

front_order_register_customer:
    path: /order/register-customer/{orderId}
    defaults: { _controller: App\Controller\Front\OrderController:registerCustomerAction }
    requirements:
        orderId: \d+

front_login_notice:
    path: /login/notice
    defaults: { _controller: App\Controller\Front\LoginController:noticeAction }
    methods: [POST]
    condition: "request.isXmlHttpRequest()"

front_download_uploaded_file:
    path: /file/{uploadedFileId}/{uploadedFilename}
    defaults: { _controller: App\Controller\Front\UploadedFileController:downloadAction }
    methods: [GET]
    requirements:
        uploadedFileId: \d+

front_customer_delivery_address_delete:
    path: /customer/delete-delivery-address/{deliveryAddressId}
    defaults:
        _controller: App\Controller\Front\CustomerController:deleteDeliveryAddressAction
        deliveryAddressId: 0
    methods: [GET]
    requirements:
        deliveryAddressId: \d+

front_product_box_tabs:
    path: /product/box-tabs/{productId}
    defaults: { _controller: App\Controller\Front\ProductController:boxTabsAction }
    methods: [GET]
    requirements:
        productId: \d+

front_watch_dog_window_form:
    path: /watch-dog/window/{productId}
    defaults: { _controller: App\Controller\Front\WatchDogController:windowFormAction }
    methods: [GET]

front_watch_dog_subscribe:
    path: /watch-dog/subscribe/
    defaults: { _controller: App\Controller\Front\WatchDogController:subscribeAction }
    methods: [POST]

front_product_search_sets:
    path: /product/search-sets/
    defaults: { _controller: App\Controller\Front\ProductController:searchSetsAction }
    condition: "request.isXmlHttpRequest()"
