parameters:
    database_driver: pdo_pgsql
    database_server_version: 10.5
    migration_database_driver: pdo_mysql
    migration_database_server_version: 5.5.62
    # Symfony's FrameworkBundle sets throw_at (error_reporting) to 0 in production by default
    debug.error_handler.throw_at: -1
    locale: cs
    shopsys.admin_locale: cs
    # Performance test parameters
    shopsys.performance_data.category.counts_by_level: [2, 4, 6]
    shopsys.performance_data.product.total_count: 40000
    shopsys.performance_data.user.count_per_domain: 100
    shopsys.performance_data.order.total_count: 50000
    shopsys.performance_data.order.item_count_per_order: 6
    shopsys.performance_test.page.duration_milliseconds.warning: 1000
    shopsys.performance_test.page.duration_milliseconds.critical: 3000
    shopsys.performance_test.page.query_count.warning: 100
    shopsys.performance_test.page.query_count.critical: 300
    shopsys.performance_test.feed.max_duration_seconds: 180
    shopsys.performance_test.feed.delivery.max_duration_seconds: 20
    shopsys.performance_test.feed.min_duration_seconds: 5
    container.autowiring.strict_mode: true
    shopsys.entity_extension.map:
        Shopsys\FrameworkBundle\Model\Advert\Advert: Shopsys\ShopBundle\Model\Advert\Advert
        Shopsys\FrameworkBundle\Model\Article\Article: Shopsys\ShopBundle\Model\Article\Article
        Shopsys\FrameworkBundle\Model\Administrator\Administrator: Shopsys\ShopBundle\Model\Administrator\Administrator
        Shopsys\FrameworkBundle\Model\Cart\Cart: Shopsys\ShopBundle\Model\Cart\Cart
        Shopsys\FrameworkBundle\Model\Category\Category: Shopsys\ShopBundle\Model\Category\Category
        Shopsys\FrameworkBundle\Model\Category\CategoryTranslation: Shopsys\ShopBundle\Model\Category\CategoryTranslation
        Shopsys\FrameworkBundle\Model\Customer\User: Shopsys\ShopBundle\Model\Customer\User
        Shopsys\FrameworkBundle\Model\Order\Order: Shopsys\ShopBundle\Model\Order\Order
        Shopsys\FrameworkBundle\Model\Order\Item\OrderItem: Shopsys\ShopBundle\Model\Order\Item\OrderItem
        Shopsys\FrameworkBundle\Model\Order\PromoCode\PromoCode: Shopsys\ShopBundle\Model\Order\PromoCode\PromoCode
        Shopsys\FrameworkBundle\Model\Transport\Transport: Shopsys\ShopBundle\Model\Transport\Transport
        Shopsys\FrameworkBundle\Model\Payment\Payment: Shopsys\ShopBundle\Model\Payment\Payment
        Shopsys\FrameworkBundle\Model\Pricing\Group\PricingGroup: Shopsys\ShopBundle\Model\Pricing\Group\PricingGroup
        Shopsys\FrameworkBundle\Model\Product\Product: Shopsys\ShopBundle\Model\Product\Product
        Shopsys\FrameworkBundle\Model\Product\ProductDomain: Shopsys\ShopBundle\Model\Product\ProductDomain
        Shopsys\FrameworkBundle\Model\Product\Brand\Brand: Shopsys\ShopBundle\Model\Product\Brand\Brand
        Shopsys\FrameworkBundle\Model\Product\Flag\Flag: Shopsys\ShopBundle\Model\Product\Flag\Flag
        Shopsys\FrameworkBundle\Model\Cart\Item\CartItem: Shopsys\ShopBundle\Model\Cart\Item\CartItem
        Shopsys\FrameworkBundle\Component\Image\Image: Shopsys\ShopBundle\Component\Image\Image
        Shopsys\FrameworkBundle\Model\Product\Parameter\ParameterValue: Shopsys\ShopBundle\Model\Product\Parameter\ParameterValue
        Shopsys\FrameworkBundle\Model\Product\Parameter\Parameter: Shopsys\ShopBundle\Model\Product\Parameter\Parameter
        Shopsys\FrameworkBundle\Model\Customer\BillingAddress: Shopsys\ShopBundle\Model\Customer\BillingAddress
        Shopsys\FrameworkBundle\Model\Customer\DeliveryAddress: Shopsys\ShopBundle\Model\Customer\DeliveryAddress
        Shopsys\FrameworkBundle\Model\Order\Status\OrderStatus: Shopsys\ShopBundle\Model\Order\Status\OrderStatus
        Shopsys\FrameworkBundle\Model\Country\Country: Shopsys\ShopBundle\Model\Country\Country
        Shopsys\FrameworkBundle\Model\Pricing\Currency\Currency: Shopsys\ShopBundle\Model\Pricing\Currency\Currency
    build-version: '0000000000000000'
    securityBcryptCost: 12
