front_about_us_info:
    path: /kontakt/
    defaults: { _controller: App\Controller\Front\AboutUsController:infoAction }

front_cart:
    path: /warenkorb/
    defaults: { _controller: App\Controller\Front\CartController:indexAction }

front_customer_edit:
    path: /kunde/angaben-bearbeiten/
    defaults: { _controller: App\Controller\Front\CustomerController:editAction }

front_customer_orders:
    path: /kunde/bestellungen/
    defaults: { _controller: App\Controller\Front\CustomerController:ordersAction }

front_customer_order_detail_registered:
    path: /kunde/bestellungen/detail/{orderNumber}
    defaults: { _controller: App\Controller\Front\CustomerController:orderDetailRegisteredAction }

front_customer_order_detail_unregistered:
    path: /bestelldetails/{urlHash}
    defaults: { _controller: App\Controller\Front\CustomerController:orderDetailUnregisteredAction }

front_login:
    path: /anmelden/
    defaults: { _controller: App\Controller\Front\LoginController:loginAction }

front_logout:
    path: /abmelden/{_csrf_token}
# controller's action is unnecessary, because firewall processes whole request

front_order_index:
    path: /bestellung/
    defaults: { _controller: App\Controller\Front\OrderController:indexAction }

front_order_paid:
    path: /order-paid/{urlHash}
    defaults: { _controller: App\Controller\Front\OrderController:paidAction }

front_order_not_paid:
    path: /order-not-paid/{urlHash}
    defaults: { _controller: App\Controller\Front\OrderController:notPaidAction }

front_order_repeat_gopay_payment:
    path: /repeat-payment/{urlHash}
    defaults: { _controller: App\Controller\Front\OrderController:repeatGoPayPaymentAction }

front_order_sent:
    path: /bestellung-bestatigen/
    defaults: { _controller: App\Controller\Front\OrderController:sentAction }

front_product_search:
    path: /suchen/
    defaults: { _controller: App\Controller\Front\ProductController:searchAction }

front_registration_register:
    path: /registration/
    defaults: { _controller: App\Controller\Front\RegistrationController:registerAction }

front_registration_reset_password:
    path: /vergessenes-passwort/
    defaults: { _controller: App\Controller\Front\CustomerPasswordController:resetPasswordAction }

front_registration_set_new_password:
    path: /neues-passwort/
    defaults: { _controller: App\Controller\Front\CustomerPasswordController:setNewPasswordAction }

front_personal_data:
    path: /personliche-informationen-ubersicht/
    defaults: { _controller: App\Controller\Front\PersonalDataController:indexAction }

front_personal_data_access:
    path: /personliche-informationen-ubersicht/{hash}/
    defaults: { _controller: App\Controller\Front\PersonalDataController:accessDisplayAction }

front_personal_data_export:
    path: /personliche-informationen-export/
    defaults: { _controller: App\Controller\Front\PersonalDataController:exportAction }

front_personal_data_access_export:
    path: /personliche-informationen-export/{hash}/
    defaults: { _controller: App\Controller\Front\PersonalDataController:accessExportAction }

front_brand_list:
    path: /tag-ubersicht/
    defaults: { _controller: App\Controller\Front\BrandController:listAction }
