front_about_us_info:
    path: /contact/
    defaults: { _controller: App\Controller\Front\AboutUsController:infoAction }

front_cart:
    path: /cart/
    defaults: { _controller: App\Controller\Front\CartController:indexAction }

front_customer_edit:
    path: /customer/edit/
    defaults: { _controller: App\Controller\Front\CustomerController:editAction }

front_customer_orders:
    path: /customer/orders/
    defaults: { _controller: App\Controller\Front\CustomerController:ordersAction }

front_customer_order_detail_registered:
    path: /customer/orders/detail/{orderNumber}
    defaults: { _controller: App\Controller\Front\CustomerController:orderDetailRegisteredAction }

front_customer_order_detail_unregistered:
    path: /order-detail/{urlHash}
    defaults: { _controller: App\Controller\Front\CustomerController:orderDetailUnregisteredAction }

front_login:
    path: /login/
    defaults: { _controller: App\Controller\Front\LoginController:loginAction }

front_logout:
    path: /logout/{_csrf_token}
# controller's action is unnecessary, because firewall processes whole request

front_order_index:
    path: /order/
    defaults: { _controller: App\Controller\Front\OrderController:indexAction }

front_order_paid:
    path: /order-payment-confirmation/{urlHash}
    defaults: { _controller: App\Controller\Front\OrderController:paidAction }

front_order_not_paid:
    path: /order-not-paid/{urlHash}
    defaults: { _controller: App\Controller\Front\OrderController:notPaidAction }

front_order_repeat_gopay_payment:
    path: /repeat-payment/{urlHash}
    defaults: { _controller: App\Controller\Front\OrderController:repeatGoPayPaymentAction }

front_order_sent:
    path: /order-confirm/
    defaults: { _controller: App\Controller\Front\OrderController:sentAction }

front_product_search:
    path: /search
    defaults: { _controller: App\Controller\Front\ProductController:searchAction }

front_registration_register:
    path: /registration/
    defaults: { _controller: App\Controller\Front\RegistrationController:registerAction }

front_registration_reset_password:
    path: /forgotten-password/
    defaults: { _controller: App\Controller\Front\CustomerPasswordController:resetPasswordAction }

front_registration_set_new_password:
    path: /new-password/
    defaults: { _controller: App\Controller\Front\CustomerPasswordController:setNewPasswordAction }

front_personal_data:
    path: /personal-information-overview/
    defaults: { _controller: App\Controller\Front\PersonalDataController:indexAction }

front_personal_data_access:
    path: /personal-information-overview/{hash}/
    defaults: { _controller: App\Controller\Front\PersonalDataController:accessDisplayAction }

front_personal_data_export:
    path: /personal-information-export/
    defaults: { _controller: App\Controller\Front\PersonalDataController:exportAction }

front_personal_data_access_export:
    path: /personal-information-export/{hash}/
    defaults: { _controller: App\Controller\Front\PersonalDataController:accessExportAction }

front_store_index:
    path: /stores/
    defaults: { _controller: App\Controller\Front\StoreController:indexAction }

front_store_detail:
    path: /stores/detail/{storeId}/
    defaults: { _controller: App\Controller\Front\StoreController:detailAction }

front_brand_list:
    path: /brands-overview/
    defaults: { _controller: App\Controller\Front\BrandController:listAction }

front_sale_product_list:
    path: /sale/{friendlyUrl}/
    defaults: { _controller: App\Controller\Front\ProductController:listBySaleCategoryAction }
