front_about_us_info:
    path: /kontakt/
    defaults: { _controller: App\Controller\Front\AboutUsController:infoAction }

front_cart:
    path: /kosik/
    defaults: { _controller: App\Controller\Front\CartController:indexAction }

front_customer_edit:
    path: /zakaznik/upravit-udaje/
    defaults: { _controller: App\Controller\Front\CustomerController:editAction }

front_customer_orders:
    path: /zakaznik/objednavky/
    defaults: { _controller: App\Controller\Front\CustomerController:ordersAction }

front_customer_order_detail_registered:
    path: /zakaznik/detail-objednavky/{orderNumber}
    defaults: { _controller: App\Controller\Front\CustomerController:orderDetailRegisteredAction }

front_customer_order_detail_unregistered:
    path: /detail-objednavky/{urlHash}
    defaults: { _controller: App\Controller\Front\CustomerController:orderDetailUnregisteredAction }

front_login:
    path: /prihlasenie/
    defaults: { _controller: App\Controller\Front\LoginController:loginAction }

front_logout:
    path: /odhlasit/{_csrf_token}
# controller's action is unnecessary, because firewall processes whole request

front_order_index:
    path: /objednavka/
    defaults: { _controller: App\Controller\Front\OrderController:indexAction }

front_order_paid:
    path: /potvrdenie-platby-objednavky/{urlHash}
    defaults: { _controller: App\Controller\Front\OrderController:paidAction }

front_order_not_paid:
    path: /nezaplatena-objednavka/{urlHash}
    defaults: { _controller: App\Controller\Front\OrderController:notPaidAction }

front_order_repeat_gopay_payment:
    path: /opakovat-platbu/{urlHash}
    defaults: { _controller: App\Controller\Front\OrderController:repeatGoPayPaymentAction }

front_order_sent:
    path: /potvrdenie-objednavky/
    defaults: { _controller: App\Controller\Front\OrderController:sentAction }

front_product_search:
    path: /hladanie
    defaults: { _controller: App\Controller\Front\ProductController:searchAction }

front_registration_register:
    path: /registracia/
    defaults: { _controller: App\Controller\Front\RegistrationController:registerAction }

front_registration_reset_password:
    path: /zabudnute-heslo/
    defaults: { _controller: App\Controller\Front\CustomerPasswordController:resetPasswordAction }

front_registration_set_new_password:
    path: /nove-heslo/
    defaults: { _controller: App\Controller\Front\CustomerPasswordController:setNewPasswordAction }

front_personal_data:
    path: /prehlad-osobnych-udajov/
    defaults: { _controller: App\Controller\Front\PersonalDataController:indexAction }

front_personal_data_access:
    path: /prehlad-osobnych-udajov/{hash}/
    defaults: { _controller: App\Controller\Front\PersonalDataController:accessDisplayAction }

front_personal_data_export:
    path: /export-osobnych-udajov/
    defaults: { _controller: App\Controller\Front\PersonalDataController:exportAction }

front_personal_data_access_export:
    path: /export-osobnych-udajov/{hash}/
    defaults: { _controller: App\Controller\Front\PersonalDataController:accessExportAction }

front_brand_list:
    path: /prehlad-znaciek/
    defaults: { _controller: App\Controller\Front\BrandController:listAction }
