monolog:
    channels: ["cron", "slow"]
    handlers:
        main:
            type: fingers_crossed
            buffer_size: 1000
            action_level: warning
            handler: nested
            excluded_404s:
                - ^/
        nested:
            type: stream
            path: 'php://stdout'
            level: info
