services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Form\:
        resource: '../src/Form/'

    App\Form\Admin\ArticleFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Article\ArticleFormType }

    App\Form\Admin\AdministratorFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Administrator\AdministratorFormType }

    App\Form\Admin\BrandFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Product\Brand\BrandFormType }

    App\Form\Admin\CategoryFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Category\CategoryFormType }

    App\Form\Admin\CustomerUserFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Customer\User\CustomerUserFormType }

    App\Form\Admin\OrderFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Order\OrderFormType }

    App\Form\Admin\PromoCodeFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\PromoCode\PromoCodeFormType }

    App\Form\Admin\TransportFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Transport\TransportFormType }

    App\Form\Admin\ProductFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Product\ProductFormType }

    App\Form\Admin\PaymentFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Payment\PaymentFormType }

    App\Form\Admin\AdvertFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Advert\AdvertFormType}

    App\Form\Admin\OrderStatusFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Order\Status\OrderStatusFormType}

    Twig_Extensions_Extension_Text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    App\Form\Admin\ParameterFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Product\Parameter\ParameterFormType}

    App\Form\Admin\CountryFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Country\CountryFormType }

    App\Form\Admin\AvailabilityFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Product\Availability\AvailabilityFormType }

    App\Form\Admin\PricingGroupFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Pricing\Group\PricingGroupFormType }

    App\Form\Admin\AllMailTemplatesFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Mail\AllMailTemplatesFormType }

    App\Form\Admin\VatFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Vat\VatFormType }
