# Example:
#-   name: product
#    class: Shopsys\FrameworkBundle\Model\Product\Product
#    types:
#        -   name: gallery
#            multiple: true
#            sizes:
#                -   name: detail
#                    width: 200
#                    height: 300
#                    crop: false
#                    occurrence: 'Front-end: Product detail, when selected'
#                    additionalSizes:
#                       - {width: 1100, height: ~, media: "(min-width: 1200px)"}
#                       - {width: 275, height: ~, media: "(max-width: 480px)"}
#                -   name: list
#                    width: 100
#                    height: 100
#                    crop: true
#                    occurrence: 'Front-end: Product detail'
#        -   name: main
#            sizes:
#                -   name: ~
#                    width: 200
#                    height: 300
#                    crop: false
#                    occurrence: 'Front-end: Product detail, Product list'

-   name: payment
    class: Shopsys\FrameworkBundle\Model\Payment\Payment
    sizes:
        -   name: ~
            width: ~
            height: 20
            crop: false
            occurrence: 'Front-end: Ordering process'

-   name: category
    class: Shopsys\FrameworkBundle\Model\Category\Category
    sizes:
        -   name: ~
            width: 56
            height: 56
            crop: false
            occurrence: 'Front-end: Product list by category'
        -   name: dropdown
            width: 70
            height: 70
            crop: false
            occurrence: 'Dropdown menu in header'

-   name: product
    class: Shopsys\FrameworkBundle\Model\Product\Product
    multiple: true
    sizes:
        -   name: ~
            width: 690
            height: ~
            crop: false
            occurrence: 'Front-end: Main image in product detail'
            additionalSizes:
                - {width: 710, height: ~, media: "(min-width: 480px) and (max-width: 768px)"}
        -   name: thumbnail
            width: 70
            height: 70
            crop: false
            occurrence: 'Front-end: Thumbnail of images under the main image in product detail, autocomplete, sets, variants, cartbox, gifts selection in cart'
        -   name: list
            width: 220
            height: 220
            crop: false
            occurrence: 'Front-end: Listing of products in section, listing of products on special offer'
            additionalSizes:
                - {width: 520, height: 520, media: "(-webkit-min-device-pixel-ratio: 2) and (min-resolution: 192dpi)"}
        -   name: gift
            width: 50
            height: 50
            crop: false
            occurrence: 'Front-end: gift on product detail'
        -   name: biggerThumbnail
            width: 101
            height: 101
            crop: false
            occurrence: 'Front-end: gift on product detail'

-   name: sliderItem
    class: Shopsys\FrameworkBundle\Model\Slider\SliderItem
    sizes:
        -   name: ~
            width: 900
            height: 230
            crop: true
            occurrence: 'Front-end: Main page slider'
            additionalSizes:
                - {width: 730, height: 230, media: "(max-width: 1023px)"}

-   name: transport
    class: Shopsys\FrameworkBundle\Model\Transport\Transport
    sizes:
        -   name: ~
            width: ~
            height: 20
            crop: false
            occurrence: 'Front-end: Ordering process'

-   name: noticer
    class: Shopsys\FrameworkBundle\Model\Advert\Advert
    sizes:
        -   name: square
            width: 429
            height: 322
            crop: true
            occurrence: 'Front-end: Banner square on homepage'
        -   name: rectangle
            width: 1320
            height: 322
            crop: true
            occurrence: 'Front-end: Banner rectangle on homepage'
            additionalSizes:
                - {width: 429, height: 322, media: "(max-width: 599px)"}
        -   name: bigBanner
            width: 190
            height: 460
            crop: true
            occurrence: 'Front-end: Big banner, six position on homepage'
        -   name: category
            width: 1180
            height: 150
            crop: true
            occurrence: 'Front-end: Banner for category'


-   name: brand
    class: Shopsys\FrameworkBundle\Model\Product\Brand\Brand
    sizes:
        -   name: ~
            width: 150
            height: 150
            crop: false
            occurrence: 'Front-end: Brand page'

-   name: store
    class: App\Model\Store\Store
    sizes:
        -   name: ~
            width: 570
            height: 380
            crop: true
            occurrence: 'Front-end: Store detail'
        -   name: list
            width: 520
            height: 245
            crop: true
            occurrence: 'Front-end: Stores list'

-   name:  blogCategory
    class: App\Model\Blog\Category\BlogCategory
    sizes:
        -   name: ~
            width: 400
            height: 250
            crop: true
            occurrence: 'Front-end: Blog category detail'

-   name:  blogArticle
    class: App\Model\Blog\Article\BlogArticle
    multiple: true
    sizes:
        -   name: ~
            width: 810
            height: 411
            crop: true
            occurrence: 'Front-end: Blog article detail'
        -   name: list
            width: 310
            height: 250
            crop: true
            occurrence: 'Front-end: Blog article list'
        -   name: thumbnail
            width: 170
            height: 170
            crop: true
            occurrence: 'Front-end: Thumbnail of images under the main image in blog article detail gallery'
