parameters:
    database_driver: pdo_pgsql
    database_server_version: 12.1
    migration_database_driver: pdo_mysql
    migration_database_server_version: 5.5.62
    # Symfony's FrameworkBundle sets throw_at (error_reporting) to 0 in production by default
    debug.error_handler.throw_at: -1
    locale: cs
    shopsys.admin_locale: cs
    # Performance test parameters
    shopsys.performance_data.category.counts_by_level: [2, 4, 6]
    shopsys.performance_data.product.total_count: 40000
    shopsys.performance_data.user.count_per_domain: 100
    shopsys.performance_data.order.total_count: 50000
    shopsys.performance_data.order.item_count_per_order: 6
    shopsys.performance_test.page.duration_milliseconds.warning: 1000
    shopsys.performance_test.page.duration_milliseconds.critical: 3000
    shopsys.performance_test.page.query_count.warning: 100
    shopsys.performance_test.page.query_count.critical: 300
    shopsys.performance_test.feed.max_duration_seconds: 180
    shopsys.performance_test.feed.delivery.max_duration_seconds: 20
    shopsys.performance_test.feed.min_duration_seconds: 5
    container.autowiring.strict_mode: true
    shopsys.image.enable_lazy_load: true
    build-version: '0000000000000000'
    securityBcryptCost: 12
    # All time values are displayed in this timezone (default is PHP timezone)
    shopsys.display_timezone: Europe/Prague
    shopsys.display_cron_overview_for_superadmin_only: false
