parameters:
    database_driver: pdo_pgsql
    database_server_version: 10.5
    migration_database_driver: pdo_mysql
    migration_database_server_version: 5.5.62
    # Symfony's FrameworkBundle sets throw_at (error_reporting) to 0 in production by default
    debug.error_handler.throw_at: -1
    locale: cs
    shopsys.admin_locale: cs
    # Performance test parameters
    shopsys.performance_data.category.counts_by_level: [2, 4, 6]
    shopsys.performance_data.product.total_count: 40000
    shopsys.performance_data.user.count_per_domain: 100
    shopsys.performance_data.order.total_count: 50000
    shopsys.performance_data.order.item_count_per_order: 6
    shopsys.performance_test.page.duration_milliseconds.warning: 1000
    shopsys.performance_test.page.duration_milliseconds.critical: 3000
    shopsys.performance_test.page.query_count.warning: 100
    shopsys.performance_test.page.query_count.critical: 300
    shopsys.performance_test.feed.max_duration_seconds: 180
    shopsys.performance_test.feed.delivery.max_duration_seconds: 20
    shopsys.performance_test.feed.min_duration_seconds: 5
    container.autowiring.strict_mode: true
    shopsys.image.enable_lazy_load: true
    shopsys.entity_extension.map:
        Shopsys\FrameworkBundle\Model\Advert\Advert: App\Model\Advert\Advert
        Shopsys\FrameworkBundle\Model\Article\Article: App\Model\Article\Article
        Shopsys\FrameworkBundle\Model\Administrator\Administrator: App\Model\Administrator\Administrator
        Shopsys\FrameworkBundle\Model\Cart\Cart: App\Model\Cart\Cart
        Shopsys\FrameworkBundle\Model\Category\Category: App\Model\Category\Category
        Shopsys\FrameworkBundle\Model\Category\CategoryTranslation: App\Model\Category\CategoryTranslation
        Shopsys\FrameworkBundle\Model\Customer\User: App\Model\Customer\User
        Shopsys\FrameworkBundle\Model\Order\Order: App\Model\Order\Order
        Shopsys\FrameworkBundle\Model\Order\Item\OrderItem: App\Model\Order\Item\OrderItem
        Shopsys\FrameworkBundle\Model\Order\PromoCode\PromoCode: App\Model\Order\PromoCode\PromoCode
        Shopsys\FrameworkBundle\Model\Transport\Transport: App\Model\Transport\Transport
        Shopsys\FrameworkBundle\Model\Payment\Payment: App\Model\Payment\Payment
        Shopsys\FrameworkBundle\Model\Pricing\Group\PricingGroup: App\Model\Pricing\Group\PricingGroup
        Shopsys\FrameworkBundle\Model\Product\Product: App\Model\Product\Product
        Shopsys\FrameworkBundle\Model\Product\ProductDomain: App\Model\Product\ProductDomain
        Shopsys\FrameworkBundle\Model\Product\Brand\Brand: App\Model\Product\Brand\Brand
        Shopsys\FrameworkBundle\Model\Product\Flag\Flag: App\Model\Product\Flag\Flag
        Shopsys\FrameworkBundle\Model\Cart\Item\CartItem: App\Model\Cart\Item\CartItem
        Shopsys\FrameworkBundle\Component\Image\Image: App\Component\Image\Image
        Shopsys\FrameworkBundle\Model\Product\Parameter\ParameterValue: App\Model\Product\Parameter\ParameterValue
        Shopsys\FrameworkBundle\Model\Product\Parameter\Parameter: App\Model\Product\Parameter\Parameter
        Shopsys\FrameworkBundle\Model\Customer\BillingAddress: App\Model\Customer\BillingAddress
        Shopsys\FrameworkBundle\Model\Customer\DeliveryAddress: App\Model\Customer\DeliveryAddress
        Shopsys\FrameworkBundle\Model\Order\Status\OrderStatus: App\Model\Order\Status\OrderStatus
        Shopsys\FrameworkBundle\Model\Country\Country: App\Model\Country\Country
        Shopsys\FrameworkBundle\Model\Pricing\Currency\Currency: App\Model\Pricing\Currency\Currency
    build-version: '0000000000000000'
    securityBcryptCost: 12
