imports:
    - { resource: parameters_test.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    CommerceGuys\Intl\NumberFormat\NumberFormatRepository: ~

    Shopsys\FrameworkBundle\Component\Localization\DateTimeFormatter:
        factory: ['@Shopsys\FrameworkBundle\Model\Localization\CustomDateTimeFormatterFactory', create]

    Shopsys\FrameworkBundle\Form\Admin\AdvancedSearch\AdvancedSearchProductFilterTranslation: '@App\Form\Admin\AdvancedSearchProductFilterTranslation'

    Shopsys\FrameworkBundle\Model\Localization\IntlCurrencyRepository: ~

    CommerceGuys\Intl\Currency\CurrencyRepositoryInterface:
        class: Shopsys\FrameworkBundle\Model\Localization\IntlCurrencyRepository

    Shopsys\FrameworkBundle\Component\EntityExtension\EntityNameResolver:
        class: Tests\App\Functional\EntityExtension\OverwritableEntityNameResolver
        arguments:
            - "%shopsys.entity_extension.map%"

    Symfony\Component\Filesystem\Filesystem: ~

    joschi127_doctrine_entity_override.event_subscriber.load_orm_metadata:
        class: Tests\App\Functional\EntityExtension\OverwritableLoadORMMetadataSubscriber
        arguments:
            - "@service_container"
            - "%shopsys.entity_extension.map%"
        tags:
            - { name: doctrine.event_subscriber, priority: -10 }

    League\Flysystem\FilesystemInterface: '@main_filesystem'

    Shopsys\FrameworkBundle\Model\Article\ArticleFactoryInterface: '@Shopsys\FrameworkBundle\Model\Article\ArticleFactory'

    Shopsys\FrameworkBundle\Model\Article\ArticleDataFactoryInterface: '@App\Model\Article\ArticleDataFactory'

    Shopsys\FrameworkBundle\Model\Administrator\AdministratorDataFactoryInterface: '@App\Model\Administrator\AdministratorDataFactory'

    Shopsys\FrameworkBundle\Model\Category\CategoryDataFactoryInterface: '@App\Model\Category\CategoryDataFactory'

    Shopsys\FrameworkBundle\Model\Cart\Watcher\CartWatcherFacade:
        class: App\Model\Cart\CartWatcher\CartWatcherFacade
        arguments:
            - '@shopsys.shop.component.flash_message.sender.front'

    Shopsys\FrameworkBundle\Model\Customer\User\CustomerUserDataFactoryInterface: '@App\Model\Customer\User\CustomerUserDataFactory'

    Shopsys\FrameworkBundle\Model\Order\OrderDataFactoryInterface: '@App\Model\Order\OrderDataFactory'

    Shopsys\FrameworkBundle\Model\Order\PromoCode\PromoCodeDataFactory: '@App\Model\Order\PromoCode\PromoCodeDataFactory'

    Shopsys\FrameworkBundle\Model\Order\PromoCode\CurrentPromoCodeFacade: '@App\Model\Order\PromoCode\CurrentPromoCodeFacade'

    Shopsys\FrameworkBundle\Model\Order\PromoCode\PromoCodeFacade: '@App\Model\Order\PromoCode\PromoCodeFacade'

    Shopsys\FrameworkBundle\Model\Order\PromoCode\Grid\PromoCodeGridFactory: '@App\Model\Order\PromoCode\Grid\PromoCodeGridFactory'

    Shopsys\FrameworkBundle\Model\Transport\TransportDataFactoryInterface: '@App\Model\Transport\TransportDataFactory'

    Shopsys\FrameworkBundle\Model\Product\Availability\AvailabilityDataFactoryInterface: '@Shopsys\FrameworkBundle\Model\Product\Availability\AvailabilityDataFactory'

    Shopsys\FrameworkBundle\Model\Payment\PaymentDataFactoryInterface: '@App\Model\Payment\PaymentDataFactory'

    Shopsys\FrameworkBundle\Model\Product\ProductDataFactoryInterface: '@App\Model\Product\ProductDataFactory'

    Shopsys\FrameworkBundle\Model\Product\Elasticsearch\ProductExportRepository: '@App\Model\Product\Elasticsearch\ProductExportRepository'

    Shopsys\FrameworkBundle\Model\Product\Brand\BrandDataFactoryInterface: '@App\Model\Product\Brand\BrandDataFactory'

    Shopsys\FrameworkBundle\Model\Product\Brand\BrandFacade: '@App\Model\Product\Brand\BrandFacade'

    Shopsys\FrameworkBundle\Model\Product\Brand\BrandRepository: '@App\Model\Product\Brand\BrandRepository'

    App\Model\AdvancedSearch\ProductAdvancedSearchConfig: ~

    Shopsys\FrameworkBundle\Model\AdvancedSearch\ProductAdvancedSearchConfig: '@App\Model\AdvancedSearch\ProductAdvancedSearchConfig'

    Shopsys\FrameworkBundle\Model\Order\OrderFacade: '@App\Model\Order\OrderFacade'

    Shopsys\FrameworkBundle\Model\Order\OrderRepository: '@App\Model\Order\OrderRepository'

    App\Model\Payment\PaymentFacade: ~

    Shopsys\FrameworkBundle\Model\Payment\PaymentFacade: '@App\Model\Payment\PaymentFacade'

    Shopsys\FrameworkBundle\Model\Payment\PaymentRepository: '@App\Model\Payment\PaymentRepository'

    Shopsys\FrameworkBundle\Model\Product\ProductFacade: '@App\Model\Product\ProductFacade'

    Shopsys\FrameworkBundle\Model\Product\ProductRepository: '@App\Model\Product\ProductRepository'

    Shopsys\FrameworkBundle\Model\Category\CategoryFacade: '@App\Model\Category\CategoryFacade'

    Shopsys\FrameworkBundle\Model\Customer\User\CustomerUserUpdateDataFactoryInterface:
        alias: App\Model\Customer\User\CustomerUserUpdateDataFactory

    Shopsys\FrameworkBundle\Model\Product\ProductFactoryInterface:
        alias: App\Model\Product\ProductFactory

    Shopsys\FrameworkBundle\Model\Order\Item\OrderItemDataFactoryInterface: '@App\Model\Order\Item\OrderItemDataFactory'

    Shopsys\FrameworkBundle\Model\Order\Item\OrderItemFactoryInterface: '@App\Model\Order\Item\OrderItemFactory'

    App\Model\Customer\User\CustomerUserUpdateDataFactory: ~

    Shopsys\FrameworkBundle\Model\Order\Preview\OrderPreviewFactory: '@App\Model\Order\Preview\OrderPreviewFactory'

    Shopsys\FrameworkBundle\Model\Category\CategoryRepository: '@App\Model\Category\CategoryRepository'

    Shopsys\FrameworkBundle\Model\Product\Pricing\ProductManualInputPriceFacade: '@App\Model\Product\Pricing\ProductManualInputPriceFacade'

    Shopsys\FrameworkBundle\Model\Customer\User\CustomerUserFacade: '@App\Model\Customer\User\CustomerUserFacade'

    Shopsys\FrameworkBundle\Model\Pricing\Group\PricingGroupFacade: '@App\Model\Pricing\Group\PricingGroupFacade'

    Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlFacade: '@App\Component\Router\FriendlyUrl\FriendlyUrlFacade'

    App\Model\Cart\CartFacade:
        arguments:
            - '@shopsys.shop.component.flash_message.sender.front'

    Shopsys\FrameworkBundle\Model\Cart\CartFacade: '@App\Model\Cart\CartFacade'

    Shopsys\FrameworkBundle\Model\Cart\Item\CartItemFactoryInterface: '@App\Model\Cart\Item\CartItemFactory'

    Shopsys\FrameworkBundle\Model\Country\CountryFacade: '@App\Model\Country\CountryFacade'

    App\Model\Product\Parameter\AdminSelectedParameter: ~

    Shopsys\FrameworkBundle\Model\Product\Parameter\ParameterRepository: '@App\Model\Product\Parameter\ParameterRepository'

    App\Component\GoogleApi\GoogleClient:
        arguments:
            - '%googleApiKey%'

    Shopsys\FrameworkBundle\Model\Product\Pricing\ProductPriceRecalculator: '@App\Model\Product\Pricing\ProductPriceRecalculator'

    Shopsys\FrameworkBundle\Model\Product\Parameter\ParameterDataFactoryInterface: '@App\Model\Product\Parameter\ParameterDataFactory'

    Shopsys\FrameworkBundle\Model\Product\Parameter\ParameterGridFactory: '@App\Model\Product\Parameter\ParameterGridFactory'

    Shopsys\FrameworkBundle\Controller\Admin\GridController:
        class: App\Controller\Admin\GridController
        tags: ['controller.service_arguments']

    App\Component\Setting\Setting: ~
    Shopsys\FrameworkBundle\Component\Setting\Setting: '@App\Component\Setting\Setting'

    Shopsys\FrameworkBundle\Model\Order\Status\Grid\OrderStatusGridFactory: '@App\Model\Order\Status\Grid\OrderStatusGridFactory'
    Shopsys\FrameworkBundle\Model\Order\Status\OrderStatusFacade: '@App\Model\Order\Status\OrderStatusFacade'
    Shopsys\FrameworkBundle\Model\Order\Status\OrderStatusRepository: '@App\Model\Order\Status\OrderStatusRepository'
    Shopsys\FrameworkBundle\Model\Order\Status\OrderStatusDataFactoryInterface: '@App\Model\Order\Status\OrderStatusDataFactory'

    Shopsys\FrameworkBundle\Model\Pricing\Currency\CurrencyFacade: '@App\Model\Pricing\Currency\CurrencyFacade'

    App\Component\Mall\MallImportOrderClient:
        arguments:
            $includeTestOrders: '%mall_includeTestOrders%'

    Shopsys\FrameworkBundle\Model\Product\Filter\ProductFilterConfigFactory: '@App\Model\Product\Filter\ProductFilterConfigFactory'

    Shopsys\FrameworkBundle\Model\Product\Filter\ParameterFilterChoiceRepository: '@App\Model\Product\Filter\ParameterFilterChoiceRepository'

    App\Model\Product\ProductOnCurrentDomainElasticFacade: ~

    Shopsys\FrameworkBundle\Model\Product\ProductOnCurrentDomainFacadeInterface: '@App\Model\Product\ProductOnCurrentDomainElasticFacade'

    App\Model\AdvancedSearch\OrderAdvancedSearchConfig: ~

    Shopsys\FrameworkBundle\Model\AdvancedSearch\OrderAdvancedSearchConfig: '@App\Model\AdvancedSearch\OrderAdvancedSearchConfig'

    App\Model\AdvancedSearchOrder\Filter\OrderTransportFilter: ~

    Shopsys\FrameworkBundle\Form\Admin\AdvancedSearch\AdvancedSearchOrderFilterTranslation: '@App\Form\Admin\AdvancedSearch\AdvancedSearchOrderFilterTranslation'

    Shopsys\ProductFeed\HeurekaBundle\Model\FeedItem\HeurekaFeedItemFactory: '@App\Model\Feed\Heureka\HeurekaFeedItemFactory'

    Shopsys\ProductFeed\GoogleBundle\Model\FeedItem\GoogleFeedItemFactory: '@App\Model\Feed\Google\GoogleFeedItemFactory'

    App\Model\Feed\FeedHelper: ~

    Shopsys\ReadModelBundle\Product\Listed\ListedProductViewFacadeInterface: '@App\Model\Product\View\ListedProductViewElasticFacade'

    Shopsys\FrameworkBundle\Model\Localization\Localization:
        arguments:
            $adminLocale: '%shopsys.admin_locale%'

    Shopsys\FrameworkBundle\Component\Router\DomainRouterFactory:
        arguments: ['%router.resource%']

    Shopsys\FrameworkBundle\Component\CurrencyFormatter\CurrencyFormatterFactory: ~

    Shopsys\FrameworkBundle\Twig\NumberFormatterExtension: '@App\Twig\NumberFormatterExtension'

    App\Model\Product\Parameter\ParameterFacade: ~

    Shopsys\FrameworkBundle\Model\Pricing\Currency\CurrencyDataFactoryInterface:
        alias: Shopsys\FrameworkBundle\Model\Pricing\Currency\CurrencyDataFactory

    Shopsys\FrameworkBundle\Model\Pricing\Currency\CurrencyFactoryInterface:
        alias: Shopsys\FrameworkBundle\Model\Pricing\Currency\CurrencyFactory

    App\Model\Transport\TransportFacade: ~

    Shopsys\FrameworkBundle\Model\Transport\TransportFacade: '@App\Model\Transport\TransportFacade'

    Shopsys\FrameworkBundle\Component\Image\ImageFacade: '@App\Component\Image\ImageFacade'
