-   name: mailTemplate
    class: Shopsys\FrameworkBundle\Model\Mail\MailTemplate
    types:
        -   name: default
            multiple: true
-   name: giftCertificate
    class: App\Model\Order\GiftCertificate\OrderGiftCertificate
    types:
        -   name: default
            multiple: false
-   name: product
    class: App\Model\Product\Product
    types:
        -   name: default
            multiple: true
