services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\ShopBundle\Model\GoPay\GoPayAvailablePaymentsCronModule:
        tags:
            - { name: shopsys.cron, hours: '3', minutes: '50', readableFrequency: '1x za den' }

    Shopsys\ShopBundle\Model\GoPay\OrderGoPayStatusUpdateCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '15', readableFrequency: '1x za hodinu' }

    Shopsys\ShopBundle\Model\PayPal\OrderPayPalStatusUpdateCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '15', readableFrequency: '1x za hodinu' }
