services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\ShopBundle\Model\Customer\Transfer\CustomerImportCronModule:
        tags:
            - { name: shopsys.cron, hours: '3', minutes: '00', instanceName: customers}

    Shopsys\ShopBundle\Model\GoPay\GoPayAvailablePaymentsCronModule:
        arguments:
            - '%gopay.config%'
        tags:
            - { name: shopsys.cron, hours: '3', minutes: '50', readableFrequency: '1x za den' }

    Shopsys\ShopBundle\Model\GoPay\OrderGoPayStatusUpdateCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '15', readableFrequency: '1x za hodinu' }

    Shopsys\ShopBundle\Model\PayPal\OrderPayPalStatusUpdateCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '15', readableFrequency: '1x za hodinu' }

    Shopsys\ShopBundle\Model\Product\Transfer\ProductImportCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*' }

    Shopsys\ShopBundle\Component\Balikobot\Pickup\DownloadPickupPlacesCronModule:
        tags:
            - { name: shopsys.cron, hours: '1', minutes: '00', readableFrequency: 'v 01:00 a při změně dopravy' }

    Shopsys\ShopBundle\Model\Customer\RecalculateUserPricingGroupCronModule:
        tags:
            - { name: shopsys.cron, hours: '23', minutes: '50', readableFrequency: 'v 23:50' }
