services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\ShopBundle\Form\:
            resource: '../../Form/'

    Shopsys\ShopBundle\Form\Admin\ArticleFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Article\ArticleFormType }

    Shopsys\ShopBundle\Form\Admin\AdministratorFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Administrator\AdministratorFormType }

    Shopsys\ShopBundle\Form\Admin\BrandFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Product\Brand\BrandFormType }

    Shopsys\ShopBundle\Form\Admin\CategoryFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Category\CategoryFormType }

    Shopsys\ShopBundle\Form\Admin\UserFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Customer\UserFormType }

    Shopsys\ShopBundle\Form\Admin\OrderFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Order\OrderFormType }

    Shopsys\ShopBundle\Form\Admin\PromoCodeFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\PromoCode\PromoCodeFormType }

    Shopsys\ShopBundle\Form\Admin\TransportFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Transport\TransportFormType }

    Shopsys\ShopBundle\Form\Admin\ProductFormTypeExtension:
        arguments:
            $flashMessageSender: '@shopsys.shop.component.flash_message.sender.admin'
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Product\ProductFormType }

    Shopsys\ShopBundle\Form\Admin\PaymentFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Payment\PaymentFormType }

    Shopsys\ShopBundle\Form\Admin\VariantFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Product\VariantFormType}

    Shopsys\ShopBundle\Form\Admin\ProductsTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\ProductsType}

    Shopsys\ShopBundle\Form\Admin\AdvertFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Advert\AdvertFormType}

    Shopsys\ShopBundle\Form\Admin\OrderStatusFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Order\Status\OrderStatusFormType}

    Twig_Extensions_Extension_Text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    Shopsys\ShopBundle\Form\Admin\ParameterFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Product\Parameter\ParameterFormType}

    Shopsys\FrameworkBundle\Form\WysiwygTypeExtension:
        class: Shopsys\ShopBundle\Form\WysiwygTypeExtension
        tags:
            - { name: form.type_extension, extended_type: FOS\CKEditorBundle\Form\Type\CKEditorType }

    Shopsys\ShopBundle\Form\Admin\CountryFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Country\CountryFormType }
