imports:
    - { resource: cron.yml }
    - { resource: forms.yml }
    - { resource: services/*.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\ShopBundle\Controller\:
        resource: '../../Controller/'
        public: true
        tags: ['controller.service_arguments']

    Shopsys\ShopBundle\:
        resource: '../../**/*{Calculation,Facade,Factory,Generator,Handler,InlineEdit,Listener,Loader,Mapper,Parser,Provider,Recalculator,Registry,Repository,Resolver,Service,Scheduler,Subscriber,Transformer,Validator,OnCurrentDomain}.php'
        exclude: '../../{Command,Controller,DependencyInjection,Form,Migrations,Resources,Twig}'

    League\Flysystem\MountManager:
        arguments:
            -
                local: '@local_filesystem'
                main: '@main_filesystem'

    Shopsys\FrameworkBundle\Controller\Admin\ProductPickerController:
        class: Shopsys\ShopBundle\Controller\Admin\ProductPickerController

    Shopsys\FrameworkBundle\Controller\Admin\ParameterController:
        class: Shopsys\ShopBundle\Controller\Admin\ParameterController

    Shopsys\FrameworkBundle\Controller\Admin\ProductController:
        class: Shopsys\ShopBundle\Controller\Admin\ProductController

    Faker\Generator:
        factory: [Faker\Factory, create, ]
        arguments: ['cs_CZ']
        calls:
            - [seed, ['%faker.seed%']]

    Shopsys\ShopBundle\Component\Balikobot\BalikobotClient:
        arguments:
            - '%balikobot%'

    Shopsys\FrameworkBundle\Component\Cron\CronFacade:
        class: Shopsys\ShopBundle\Component\Cron\CronFacade
        arguments:
            - '@monolog.logger.cron'

    Shopsys\ShopBundle\Component\Rest\RestClient:
        class: Shopsys\ShopBundle\Component\Rest\RestClient
        factory: 'Shopsys\ShopBundle\Component\Rest\RestClientFactory:create'
        arguments:
            - '%transfer_host%'
            - '%transfer_username%'
            - '%transfer_password%'
            - '%transfer_enabled%'

    Shopsys\ShopBundle\Component\Transfer\Logger\TransferLoggerFactory:
        arguments:
            - '@monolog.logger.cron'

    Shopsys\ShopBundle\Component\Transfer\TransferConfig:
        arguments:
            - '%transfer_host%'
            - '%transfer_username%'
            - '%transfer_password%'
            - '%transfer_enabled%'

    Shopsys\ShopBundle\Component\Transfer\TransferCronModuleDependency: ~

    Shopsys\ShopBundle\Form\Front\Order\DomainAwareOrderFlowFactory: ~

    Shopsys\FrameworkBundle\Model\Order\OrderFlowFactoryInterface: '@Shopsys\ShopBundle\Form\Front\Order\DomainAwareOrderFlowFactory'

    Shopsys\FrameworkBundle\Model\Article\ArticleDataFactoryInterface: '@Shopsys\ShopBundle\Model\Article\ArticleDataFactory'

    Shopsys\ShopBundle\Model\Category\CurrentCategoryResolver: ~

    League\Flysystem\FilesystemInterface: '@main_filesystem'

    Shopsys\FrameworkBundle\Model\Administrator\AdministratorDataFactoryInterface: '@Shopsys\ShopBundle\Model\Administrator\AdministratorDataFactory'

    Shopsys\FrameworkBundle\Model\Category\CategoryDataFactoryInterface: '@Shopsys\ShopBundle\Model\Category\CategoryDataFactory'

    Shopsys\FrameworkBundle\Model\Customer\UserDataFactoryInterface: '@Shopsys\ShopBundle\Model\Customer\UserDataFactory'

    Shopsys\ShopBundle\Model\Localization\Localization:
        arguments:
            $adminLocale: '%shopsys.admin_locale%'

    Shopsys\FrameworkBundle\Model\Localization\Localization: '@Shopsys\ShopBundle\Model\Localization\Localization'

    Shopsys\FrameworkBundle\Model\Order\OrderDataFactoryInterface: '@Shopsys\ShopBundle\Model\Order\OrderDataFactory'

    Shopsys\FrameworkBundle\Model\Order\Item\OrderItemDataFactoryInterface: '@Shopsys\ShopBundle\Model\Order\Item\OrderItemDataFactory'

    Shopsys\ShopBundle\Model\Order\OrderDataMapper: ~

    Shopsys\FrameworkBundle\Model\Order\OrderDataMapper: '@Shopsys\ShopBundle\Model\Order\OrderDataMapper'

    Shopsys\FrameworkBundle\Model\Transport\TransportDataFactoryInterface: '@Shopsys\ShopBundle\Model\Transport\TransportDataFactory'

    Shopsys\FrameworkBundle\Model\Payment\PaymentDataFactoryInterface: '@Shopsys\ShopBundle\Model\Payment\PaymentDataFactory'

    Shopsys\FrameworkBundle\Model\Product\ProductDataFactoryInterface: '@Shopsys\ShopBundle\Model\Product\ProductDataFactory'

    Shopsys\FrameworkBundle\Model\Product\ProductOnCurrentDomainFacadeInterface: '@Shopsys\ShopBundle\Model\Product\ProductOnCurrentDomainElasticFacade'

    Shopsys\FrameworkBundle\Model\Product\Search\Export\ProductSearchExportRepository: '@Shopsys\FrameworkBundle\Model\Product\Search\Export\ProductSearchExportWithFilterRepository'

    Shopsys\FrameworkBundle\Model\Product\Brand\BrandDataFactoryInterface: '@Shopsys\ShopBundle\Model\Product\Brand\BrandDataFactory'

    Shopsys\ShopBundle\DataFixtures\ProductDataFixtureReferenceInjector: ~

    Shopsys\ShopBundle\DataFixtures\Demo\ProductDataFixtureLoader: ~

    Shopsys\ShopBundle\DataFixtures\Demo\ProductParametersFixtureLoader: ~

    Shopsys\ShopBundle\DataFixtures\Performance\CategoryDataFixture:
        arguments:
            - "%shopsys.performance_data.category.counts_by_level%"

    Shopsys\ShopBundle\DataFixtures\Performance\OrderDataFixture:
        arguments:
            - "%shopsys.performance_data.order.total_count%"
            - "%shopsys.performance_data.order.item_count_per_order%"

    Shopsys\ShopBundle\DataFixtures\Performance\ProductDataFixture:
        arguments:
            - "%shopsys.performance_data.product.total_count%"

    Shopsys\ShopBundle\DataFixtures\Performance\UserDataFixture:
        arguments:
            - "%shopsys.performance_data.user.count_per_domain%"

    Shopsys\ShopBundle\DataFixtures\Demo\ImageDataFixture:
        arguments:
            - '%shopsys.data_fixtures_images.resources_dir%'
            - '%shopsys.image_dir%'
            - '%shopsys.domain_images_dir%'
        tags: ['doctrine.fixture.orm']

    Shopsys\ShopBundle\DataFixtures\Demo\ProductDataFixtureCsvReader:
        arguments:
            - '%shopsys.data_fixtures.resource_products_filepath%'

    Shopsys\ShopBundle\DataFixtures\Demo\UserDataFixtureLoader:
        arguments:
            - '%shopsys.data_fixtures.resource_customers_filepath%'

    Shopsys\ShopBundle\Model\AdvancedSearch\ProductAdvancedSearchConfig: ~

    Shopsys\FrameworkBundle\Model\AdvancedSearch\ProductAdvancedSearchConfig: '@Shopsys\ShopBundle\Model\AdvancedSearch\ProductAdvancedSearchConfig'

    Shopsys\FrameworkBundle\Model\Order\OrderFacade: '@Shopsys\ShopBundle\Model\Order\OrderFacade'

    Shopsys\FrameworkBundle\Model\Order\OrderRepository: '@Shopsys\ShopBundle\Model\Order\OrderRepository'

    Shopsys\FrameworkBundle\Model\Payment\PaymentFacade: '@Shopsys\ShopBundle\Model\Payment\PaymentFacade'

    Shopsys\FrameworkBundle\Model\Payment\PaymentRepository: '@Shopsys\ShopBundle\Model\Payment\PaymentRepository'

    Shopsys\ShopBundle\Model\GoPay\GoPayClientFactory:
        arguments:
            - '%gopay.config%'

    Shopsys\ShopBundle\Model\GoPay\PaymentMethod\GoPayPaymentMethodFacade:
        public: true

    Shopsys\FrameworkBundle\Model\Product\ProductFacade: '@Shopsys\ShopBundle\Model\Product\ProductFacade'

    Shopsys\FrameworkBundle\Model\Product\ProductRepository: '@Shopsys\ShopBundle\Model\Product\ProductRepository'

    Shopsys\ShopBundle\Model\Product\LastVisitedProducts\ProductDetailVisitListener:
        tags:
            - { name: kernel.event_subscriber }

    Shopsys\ShopBundle\Model\PayPal\PayPalClient:
        arguments:
            - '%payPalClientId%'
            - '%payPalClientSecret%'

    Shopsys\FrameworkBundle\Model\Product\ProductCachedAttributesFacade:
        class: Shopsys\ShopBundle\Model\Product\ProductCachedAttributesFacade

    Shopsys\FrameworkBundle\Model\Product\ProductFactory: '@Shopsys\ShopBundle\Model\Product\ProductFactory'

    Shopsys\FrameworkBundle\Model\Product\ProductVariantFacade: '@Shopsys\ShopBundle\Model\Product\ProductVariantFacade'

    Shopsys\FrameworkBundle\Model\Product\Parameter\ParameterFacade: '@Shopsys\ShopBundle\Model\Product\Parameter\ParameterFacade'

    Shopsys\FrameworkBundle\Model\Transport\TransportFacade: '@Shopsys\ShopBundle\Model\Transport\TransportFacade'

    Shopsys\FrameworkBundle\Model\Transport\TransportRepository: '@Shopsys\ShopBundle\Model\Transport\TransportRepository'

    Shopsys\FrameworkBundle\Component\Cron\CronModuleFacade: '@Shopsys\ShopBundle\Component\Cron\CronModuleFacade'

    Shopsys\FrameworkBundle\Model\Country\CountryFacade: '@Shopsys\ShopBundle\Model\Country\CountryFacade'

    Shopsys\FrameworkBundle\Model\Country\CountryRepository: '@Shopsys\ShopBundle\Model\Country\CountryRepository'

    Shopsys\FrameworkBundle\Model\Transport\TransportVisibilityCalculation: '@Shopsys\ShopBundle\Model\Transport\TransportVisibilityCalculation'
