services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    CommerceGuys\Intl\NumberFormat\NumberFormatRepository: ~

    Shopsys\FrameworkBundle\Component\Localization\DateTimeFormatter:
        factory: ['@Shopsys\FrameworkBundle\Model\Localization\CustomDateTimeFormatterFactory', create]

    Shopsys\FrameworkBundle\Form\Admin\AdvancedSearch\AdvancedSearchProductFilterTranslation: '@Shopsys\ShopBundle\Form\Admin\AdvancedSearchProductFilterTranslation'

    Shopsys\FrameworkBundle\Model\Localization\IntlCurrencyRepository: ~

    CommerceGuys\Intl\Currency\CurrencyRepositoryInterface:
        class: Shopsys\FrameworkBundle\Model\Localization\IntlCurrencyRepository

    Shopsys\FrameworkBundle\Component\EntityExtension\EntityNameResolver:
        class: Tests\ShopBundle\Functional\EntityExtension\OverwritableEntityNameResolver
        arguments:
            - "%shopsys.entity_extension.map%"

    Symfony\Component\Filesystem\Filesystem: ~

    joschi127_doctrine_entity_override.event_subscriber.load_orm_metadata:
        class: Tests\ShopBundle\Functional\EntityExtension\OverwritableLoadORMMetadataSubscriber
        arguments:
            - "@service_container"
            - "%shopsys.entity_extension.map%"
        tags:
            - { name: doctrine.event_subscriber, priority: -10 }

    League\Flysystem\FilesystemInterface: '@main_filesystem'

    Shopsys\FrameworkBundle\Model\Article\ArticleFactoryInterface: '@Shopsys\FrameworkBundle\Model\Article\ArticleFactory'

    Shopsys\FrameworkBundle\Model\Article\ArticleDataFactoryInterface: '@Shopsys\ShopBundle\Model\Article\ArticleDataFactory'

    Shopsys\FrameworkBundle\Model\Administrator\AdministratorDataFactoryInterface: '@Shopsys\ShopBundle\Model\Administrator\AdministratorDataFactory'

    Shopsys\FrameworkBundle\Model\Category\CategoryDataFactoryInterface: '@Shopsys\ShopBundle\Model\Category\CategoryDataFactory'

    Shopsys\FrameworkBundle\Model\Cart\Watcher\CartWatcherFacade:
        class: Shopsys\ShopBundle\Model\Cart\CartWatcher\CartWatcherFacade
        arguments:
            - '@shopsys.shop.component.flash_message.sender.front'

    Shopsys\FrameworkBundle\Model\Customer\UserDataFactoryInterface: '@Shopsys\ShopBundle\Model\Customer\UserDataFactory'

    Shopsys\FrameworkBundle\Model\Order\OrderDataFactoryInterface: '@Shopsys\ShopBundle\Model\Order\OrderDataFactory'

    Shopsys\FrameworkBundle\Model\Order\PromoCode\PromoCodeDataFactory: '@Shopsys\ShopBundle\Model\Order\PromoCode\PromoCodeDataFactory'

    Shopsys\FrameworkBundle\Model\Order\PromoCode\CurrentPromoCodeFacade: '@Shopsys\ShopBundle\Model\Order\PromoCode\CurrentPromoCodeFacade'

    Shopsys\FrameworkBundle\Model\Order\PromoCode\PromoCodeFacade: '@Shopsys\ShopBundle\Model\Order\PromoCode\PromoCodeFacade'

    Shopsys\FrameworkBundle\Model\Order\PromoCode\Grid\PromoCodeGridFactory: '@Shopsys\ShopBundle\Model\Order\PromoCode\Grid\PromoCodeGridFactory'

    Shopsys\FrameworkBundle\Model\Transport\TransportDataFactoryInterface: '@Shopsys\ShopBundle\Model\Transport\TransportDataFactory'

    Shopsys\FrameworkBundle\Model\Product\Availability\AvailabilityDataFactoryInterface: '@Shopsys\FrameworkBundle\Model\Product\Availability\AvailabilityDataFactory'

    Shopsys\FrameworkBundle\Model\Payment\PaymentDataFactoryInterface: '@Shopsys\ShopBundle\Model\Payment\PaymentDataFactory'

    Shopsys\FrameworkBundle\Model\Product\ProductDataFactoryInterface: '@Shopsys\ShopBundle\Model\Product\ProductDataFactory'

    Shopsys\FrameworkBundle\Model\Product\Search\Export\ProductSearchExportWithFilterRepository: '@Shopsys\ShopBundle\Model\Product\Search\Export\ProductSearchExportWithFilterRepository'

    Shopsys\FrameworkBundle\Model\Product\Brand\BrandDataFactoryInterface: '@Shopsys\ShopBundle\Model\Product\Brand\BrandDataFactory'

    Shopsys\FrameworkBundle\Model\Product\Brand\BrandFacade: '@Shopsys\ShopBundle\Model\Product\Brand\BrandFacade'

    Shopsys\FrameworkBundle\Model\Product\Brand\BrandRepository: '@Shopsys\ShopBundle\Model\Product\Brand\BrandRepository'

    Shopsys\ShopBundle\Model\AdvancedSearch\ProductAdvancedSearchConfig: ~

    Shopsys\FrameworkBundle\Model\AdvancedSearch\ProductAdvancedSearchConfig: '@Shopsys\ShopBundle\Model\AdvancedSearch\ProductAdvancedSearchConfig'

    Shopsys\FrameworkBundle\Model\Order\OrderFacade: '@Shopsys\ShopBundle\Model\Order\OrderFacade'

    Shopsys\FrameworkBundle\Model\Order\OrderRepository: '@Shopsys\ShopBundle\Model\Order\OrderRepository'

    Shopsys\ShopBundle\Model\Payment\PaymentFacade: ~

    Shopsys\FrameworkBundle\Model\Payment\PaymentFacade: '@Shopsys\ShopBundle\Model\Payment\PaymentFacade'

    Shopsys\FrameworkBundle\Model\Payment\PaymentRepository: '@Shopsys\ShopBundle\Model\Payment\PaymentRepository'

    Shopsys\FrameworkBundle\Model\Product\ProductFacade: '@Shopsys\ShopBundle\Model\Product\ProductFacade'

    Shopsys\FrameworkBundle\Model\Product\ProductRepository: '@Shopsys\ShopBundle\Model\Product\ProductRepository'

    Shopsys\FrameworkBundle\Model\Category\CategoryFacade: '@Shopsys\ShopBundle\Model\Category\CategoryFacade'

    Shopsys\FrameworkBundle\Model\Customer\CustomerDataFactoryInterface:
        alias: Shopsys\ShopBundle\Model\Customer\CustomerDataFactory

    Shopsys\FrameworkBundle\Model\Product\ProductFactoryInterface:
        alias: Shopsys\ShopBundle\Model\Product\ProductFactory

    Shopsys\FrameworkBundle\Model\Order\Item\OrderItemDataFactoryInterface: '@Shopsys\ShopBundle\Model\Order\Item\OrderItemDataFactory'

    Shopsys\FrameworkBundle\Model\Order\Item\OrderItemFactoryInterface: '@Shopsys\ShopBundle\Model\Order\Item\OrderItemFactory'

    Shopsys\ShopBundle\Model\Customer\CustomerDataFactory: ~

    Shopsys\FrameworkBundle\Model\Order\Preview\OrderPreviewFactory: '@Shopsys\ShopBundle\Model\Order\Preview\OrderPreviewFactory'

    Shopsys\FrameworkBundle\Model\Category\CategoryRepository: '@Shopsys\ShopBundle\Model\Category\CategoryRepository'

    Shopsys\FrameworkBundle\Model\Product\Pricing\ProductManualInputPriceFacade: '@Shopsys\ShopBundle\Model\Product\Pricing\ProductManualInputPriceFacade'

    Shopsys\FrameworkBundle\Model\Customer\CustomerFacade: '@Shopsys\ShopBundle\Model\Customer\CustomerFacade'

    Shopsys\FrameworkBundle\Model\Pricing\Group\PricingGroupFacade: '@Shopsys\ShopBundle\Model\Pricing\Group\PricingGroupFacade'

    Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlFacade: '@Shopsys\ShopBundle\Component\Router\FriendlyUrl\FriendlyUrlFacade'

    Shopsys\ShopBundle\Model\Cart\CartFacade:
        arguments:
            - '@shopsys.shop.component.flash_message.sender.front'

    Shopsys\ShopBundle\Model\Customer\BushmanCustomPasswordEncoder:
        arguments:
            - '%securityBcryptCost%'

    Shopsys\FrameworkBundle\Model\Cart\CartFacade: '@Shopsys\ShopBundle\Model\Cart\CartFacade'

    Shopsys\FrameworkBundle\Model\Cart\Item\CartItemFactoryInterface: '@Shopsys\ShopBundle\Model\Cart\Item\CartItemFactory'

    Shopsys\FrameworkBundle\Model\Country\CountryFacade: '@Shopsys\ShopBundle\Model\Country\CountryFacade'

    Shopsys\ShopBundle\Model\Product\Parameter\AdminSelectedParameter: ~

    Shopsys\FrameworkBundle\Model\Product\Parameter\ParameterRepository: '@Shopsys\ShopBundle\Model\Product\Parameter\ParameterRepository'

    Shopsys\ShopBundle\Component\GoogleApi\GoogleClient:
        arguments:
            - '%googleApiKey%'

    Shopsys\FrameworkBundle\Model\Product\Pricing\ProductPriceRecalculator: '@Shopsys\ShopBundle\Model\Product\Pricing\ProductPriceRecalculator'

    Shopsys\FrameworkBundle\Model\Product\Parameter\ParameterDataFactoryInterface: '@Shopsys\ShopBundle\Model\Product\Parameter\ParameterDataFactory'

    Shopsys\FrameworkBundle\Model\Product\Parameter\ParameterGridFactory: '@Shopsys\ShopBundle\Model\Product\Parameter\ParameterGridFactory'

    Shopsys\FrameworkBundle\Controller\Admin\GridController:
        class: Shopsys\ShopBundle\Controller\Admin\GridController
        tags: ['controller.service_arguments']

    Shopsys\ShopBundle\Component\Setting\Setting: ~
    Shopsys\FrameworkBundle\Component\Setting\Setting: '@Shopsys\ShopBundle\Component\Setting\Setting'

    Shopsys\FrameworkBundle\Model\Order\Status\Grid\OrderStatusGridFactory: '@Shopsys\ShopBundle\Model\Order\Status\Grid\OrderStatusGridFactory'
    Shopsys\FrameworkBundle\Model\Order\Status\OrderStatusFacade: '@Shopsys\ShopBundle\Model\Order\Status\OrderStatusFacade'
    Shopsys\FrameworkBundle\Model\Order\Status\OrderStatusRepository: '@Shopsys\ShopBundle\Model\Order\Status\OrderStatusRepository'
    Shopsys\FrameworkBundle\Model\Order\Status\OrderStatusDataFactoryInterface: '@Shopsys\ShopBundle\Model\Order\Status\OrderStatusDataFactory'

    Shopsys\FrameworkBundle\Model\Pricing\Currency\CurrencyFacade: '@Shopsys\ShopBundle\Model\Pricing\Currency\CurrencyFacade'

    Shopsys\ShopBundle\Component\Mall\MallImportOrderClient:
        arguments:
            $includeTestOrders: '%mall_includeTestOrders%'

    Shopsys\FrameworkBundle\Model\Product\Filter\ProductFilterConfigFactory: '@Shopsys\ShopBundle\Model\Product\Filter\ProductFilterConfigFactory'

    Shopsys\FrameworkBundle\Model\Product\Filter\ParameterFilterChoiceRepository: '@Shopsys\ShopBundle\Model\Product\Filter\ParameterFilterChoiceRepository'

    Shopsys\ShopBundle\Model\Product\ProductOnCurrentDomainElasticFacade: ~

    Shopsys\FrameworkBundle\Model\Product\ProductOnCurrentDomainFacadeInterface: '@Shopsys\ShopBundle\Model\Product\ProductOnCurrentDomainElasticFacade'

    Shopsys\ShopBundle\Model\AdvancedSearch\OrderAdvancedSearchConfig: ~

    Shopsys\FrameworkBundle\Model\AdvancedSearch\OrderAdvancedSearchConfig: '@Shopsys\ShopBundle\Model\AdvancedSearch\OrderAdvancedSearchConfig'

    Shopsys\ShopBundle\Model\AdvancedSearchOrder\Filter\OrderTransportFilter: ~

    Shopsys\FrameworkBundle\Form\Admin\AdvancedSearch\AdvancedSearchOrderFilterTranslation: '@Shopsys\ShopBundle\Form\Admin\AdvancedSearch\AdvancedSearchOrderFilterTranslation'

    Shopsys\ProductFeed\HeurekaBundle\Model\FeedItem\HeurekaFeedItemFactory: '@Shopsys\ShopBundle\Model\Feed\Heureka\HeurekaFeedItemFactory'

    Shopsys\ProductFeed\GoogleBundle\Model\FeedItem\GoogleFeedItemFactory: '@Shopsys\ShopBundle\Model\Feed\Google\GoogleFeedItemFactory'

    Shopsys\ShopBundle\Model\Feed\FeedHelper: ~

    Shopsys\ReadModelBundle\Product\Listed\ListedProductViewFacadeInterface: '@Shopsys\ShopBundle\Model\Product\View\ListedProductViewElasticFacade'

    Shopsys\FrameworkBundle\Model\Localization\Localization:
        arguments:
            $adminLocale: '%shopsys.admin_locale%'

    Shopsys\FrameworkBundle\Component\Router\DomainRouterFactory:
        arguments: ['%router.resource%']

    Shopsys\FrameworkBundle\Component\CurrencyFormatter\CurrencyFormatterFactory: ~

    Shopsys\FrameworkBundle\Twig\NumberFormatterExtension: '@Shopsys\ShopBundle\Twig\NumberFormatterExtension'

    Shopsys\ShopBundle\Model\Product\Parameter\ParameterFacade: ~

    Shopsys\FrameworkBundle\Model\Pricing\Currency\CurrencyDataFactoryInterface:
        alias: Shopsys\FrameworkBundle\Model\Pricing\Currency\CurrencyDataFactory

    Shopsys\FrameworkBundle\Model\Pricing\Currency\CurrencyFactoryInterface:
        alias: Shopsys\FrameworkBundle\Model\Pricing\Currency\CurrencyFactory

    Shopsys\ShopBundle\Model\Transport\TransportFacade: ~

    Shopsys\FrameworkBundle\Model\Transport\TransportFacade: '@Shopsys\ShopBundle\Model\Transport\TransportFacade'
