apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-default-config
data:
    nginx.conf: |
        user  nginx;
        worker_processes auto;

        error_log  /var/log/nginx/error.log warn;
        pid        /var/run/nginx.pid;

        events {
            # determines how much clients will be served per worker
            # max clients = worker_connections * worker_processes
            # max clients is also limited by the number of socket connections available on the system (~64k)
            worker_connections 30000;
        }

        http {
            include       /etc/nginx/mime.types;
            default_type  application/octet-stream;

            log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                             '$status $body_bytes_sent "$http_referer" '
                             '"$http_user_agent" "$http_x_forwarded_for"';

            access_log  /var/log/nginx/access.log  main;

            sendfile        on;
            #tcp_nopush     on;

            keepalive_timeout  65;

            include /etc/nginx/conf.d/*.conf;
        }
