services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\ShopBundle\Command\:
        resource: '../../../Command'

    Shopsys\ShopBundle\Command\MigrateCustomersPasswordsCommand:
        class: Shopsys\ShopBundle\Command\Migration\MigrateCustomersPasswordsCommand
        arguments:
            - '%kernel.project_dir%'

    Shopsys\FrameworkBundle\Command\RedisCleanCacheOldCommand: ~

    Shopsys\ShopBundle\Command\MaintenanceModeCommand:
        arguments:
            - '@shopsys.shop.maintenance_cache_provider'
