services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\ShopBundle\Command\:
        resource: '../../../Command'

    Shopsys\ShopBundle\Command\MigrateCustomersPasswordsCommand:
        class: Shopsys\ShopBundle\Command\Migration\MigrateCustomersPasswordsCommand
        arguments:
            - '%kernel.project_dir%'

    Shopsys\ShopBundle\Command\MaintenanceModeCommand:
        arguments:
            - '@shopsys.shop.maintenance_cache_provider'

    Shopsys\ShopBundle\Command\ExtendedClassesAnnotationsCommand:
        arguments:
            - '%shopsys.root_dir%'

    Shopsys\FrameworkBundle\Command\ExtendedClassesAnnotationsCommand: '@Shopsys\ShopBundle\Command\ExtendedClassesAnnotationsCommand'

    Shopsys\FrameworkBundle\Component\ClassExtension\ClassExtensionRegistry:
        arguments:
            - '%shopsys.entity_extension.map%'
            - '%shopsys.framework.root_dir%'
