services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\ShopBundle\Twig\:
        resource: '../../Twig/'

    Shopsys\ShopBundle\Twig\ImageExtension:
        arguments: ['%shopsys.front_design_image_url_prefix%', '@assets._default_package']

    Shopsys\ShopBundle\Twig\DomainExtension:
        arguments:
            - '%shopsys.domain_images_url_prefix%'

    Shopsys\ShopBundle\Twig\PriceExtension: ~
