snc_redis:
    clients:
        bestselling_products:
            type: 'phpredis'
            alias: 'bestselling_products'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%bestselling_products_'
        doctrine_metadata:
            type: 'phpredis'
            alias: 'doctrine_metadata'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%doctrine_metadata_'
        doctrine_query:
            type: 'phpredis'
            alias: 'doctrine_query'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%doctrine_query_'
        global:
            type: 'phpredis'
            alias: 'global'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%'
        session:
            type: 'phpredis'
            alias: 'session'
            dsn: 'redis://%redis_host%'
        framework_annotations:
            type: 'phpredis'
            alias: 'framework_annotations'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:cache:framework:annotations:'
    session:
        client: 'session'
        prefix: '%env(REDIS_PREFIX)%session_'
