apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: cron-executor-images
spec:
    concurrencyPolicy: Forbid
    failedJobsHistoryLimit: 0
    successfulJobsHistoryLimit: 0
    startingDeadlineSeconds: 600 # Prevents disable creating cron jobs
    schedule: "*/5 * * * *"
    jobTemplate:
        spec:
            backoffLimit: 0
            activeDeadlineSeconds: 86400
            template:
                spec:
                    volumes:
                        -   name: domains-urls
                            configMap:
                                name: domains-urls
                        -   name: parameters
                            configMap:
                                name: parameters
                    containers:
                        -   name: cron-executor-images
                            image: "{{TAG}}"
                            args:
                                - /bin/sh
                                - -c
                                - ./phing cron-images > /dev/null 2>&1
                            securityContext:
                                runAsUser: 33
                            imagePullPolicy: Always
                            workingDir: /var/www/html
                            volumeMounts:
                                -   name: domains-urls
                                    mountPath: /var/www/html/{{DOMAINS_URLS_FILEPATH}}
                                    subPath: "{{DOMAINS_URLS_FILENAME}}"
                                -   name: parameters
                                    mountPath: /var/www/html/{{PARAMETERS_FILEPATH}}
                                    subPath: "{{PARAMETERS_FILENAME}}"
                    restartPolicy: Never
                    imagePullSecrets:
                        -   name: dockerregistry
